language: haxe

haxe:
  - 3.2.0
  - development

env: 
  - TARGET=flash
  - TARGET=neko
  - TARGET=cpp
  - TARGET=html5
  
matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install munit > /dev/null
  - haxelib install hamcrest > /dev/null
  - haxelib install lime > /dev/null
  - haxelib install openfl > /dev/null
  - haxelib install hxcpp > /dev/null
  - haxelib install systools > /dev/null
  - haxelib install nape > /dev/null
  - haxelib install task > /dev/null
  - haxelib install hscript > /dev/null
  - haxelib install poly2trihx > /dev/null
  - haxelib git spinehaxe https://github.com/bendmorris/spinehaxe > /dev/null
  - haxelib git openfl-bitfive https://github.com/YellowAfterlife/openfl-bitfive > /dev/null
  - haxelib git firetongue https://github.com/larsiusprime/firetongue > /dev/null
  - haxelib git flixel https://github.com/HaxeFlixel/flixel > /dev/null
  - haxelib git flixel-tools https://github.com/HaxeFlixel/flixel-tools > /dev/null
  - haxelib git flixel-demos https://github.com/HaxeFlixel/flixel-demos dev > /dev/null
  - haxelib git flixel-ui https://github.com/HaxeFlixel/flixel-ui dev > /dev/null
  - haxelib dev flixel-addons $TRAVIS_BUILD_DIR
  - haxelib list

script:
  - cd ~/haxe/lib/flixel/git/tests
  - haxe RunTravis.hxml
  - neko RunTravis.n
