package flixel.addons.api.gamejolt;

import gamejolt.formats.*;
import gamejolt.types.*;
import haxe.Http;
import haxe.Json.parse;
import lime.app.Event;
import openfl.events.*;

using Lambda;
using StringTools;

/**
 * The general GameJolt class you can be able to make calls to its API from.
 * @see 	https://postman.com/gamerpablito/gamejolt-api-workspace
 * @see 	https://gamejolt.com/game-api
 */
class FlxGameJoltRequest
{
	/**
	 * The actual URL created by the parsing of the current `call`.
	 */
	public var url(get, never):String;
	
	/**
	 * The last response generated by `send()` spawns here.
	 */
	public var lastResponse(default, null):FlxGameJoltResponse = {success: false, message: "No response has been received yet"};
	
	/**
	 * The current instruction `this` is willing to execute. Cannot be modified while `executing == true`.
	 */
	public var call(default, set):FlxGameJoltRequestType;
	
	/**
	 * Whether if the current `url` is being executed by `send()` or not.
	 */
	public var executing(default, null):Bool = false;
	
	/**
	 * An event dispatcher you can set up to be called by `send()` when the current execution ends successfully.
	 */
	public var onComplete:Event<FlxGameJoltResponse->Void> = new Event<FlxGameJoltResponse->Void>();
	
	/**
	 * An event dispatcher you can set up to be called by `send()` while the current execution is progressing.
	 */
	public var onProgress:Event<Float->Float->Void> = new Event<Float->Float->Void>();
	
	/**
	 * An event dispatcher you can set up to be called by `send()` when the current execution ends with an error of any kind.
	 */
	public var onError:Event<String->Void> = new Event<String->Void>();
	
	public function new(Call:FlxGameJoltRequestType)
		call = Call;
		
	function get_url():String
		return sign('https://api.gamejolt.com/api/game/v1_2${parseType(call)}');
		
	function set_call(value:FlxGameJoltRequestType):FlxGameJoltRequestType
	{
		if (executing)
			return call;
		return call = value;
	}
	
	/**
	 * Sends the current `call` to the GameJolt API to return a `FlxGameJoltResponse` from it, if `executing == false`.
	 * @param   async  Whether to run the request asynchronously or not.
	 */
	public function send(async:Bool)
	{
		if (executing)
			return;
		executing = true;
		
		if (async)
		{
			var loader = new openfl.net.URLLoader();
			loader.addEventListener(openfl.events.Event.COMPLETE, function(complete)
			{
				lastResponse = formatImages(parse(cast(loader.data, String)).response);
				if (lastResponse.message != null)
					onError.dispatch('Response Error: ${lastResponse.message}');
				else
					onComplete.dispatch(lastResponse);
				executing = false;
			});
			loader.addEventListener(ProgressEvent.PROGRESS, progress -> onProgress.dispatch(progress.bytesLoaded, progress.bytesTotal));
			loader.addEventListener(IOErrorEvent.IO_ERROR, function(ioError)
			{
				lastResponse = {success: false, message: 'IO Error: ${ioError.text}'};
				onError.dispatch(lastResponse.message);
				executing = false;
			});
			loader.addEventListener(SecurityErrorEvent.SECURITY_ERROR, securityError ->
			{
				lastResponse = {success: false, message: 'Security Error: ${securityError.text}'};
				onError.dispatch(lastResponse.message);
				executing = false;
			});
			loader.load(new openfl.net.URLRequest(url));
		}
		else
		{
			var loader:Http = new Http(url);
			loader.onData = function(data)
			{
				lastResponse = formatImages(cast parse(data).response);
				if (lastResponse.message != null)
					onError.dispatch('Response Error: ${lastResponse.message}');
				else
					onComplete.dispatch(lastResponse);
				executing = false;
			};
			loader.onError = function(error)
			{
				lastResponse = {success: false, message: 'Request Error: ${error}'};
				onError.dispatch(lastResponse.message);
				executing = false;
			};
			loader.request(false);
		}
	}
	
	/**
	 * Makes retrieved images to have a better resolution.
	 * @param   oldRes  The `FlxGameJoltResponse` to be modified.
	 * @return  A new `FlxGameJoltResponse` with every Image URL modified for a better resolution when requested.
	 */
	function formatImages(res:FlxGameJoltResponse):FlxGameJoltResponse
	{
		if (res.users != null)
			res.users.iter(u -> u.avatar_url = '${u.avatar_url.substring(0, 32)}1000${u.avatar_url.substr(34)}'.replace(".jpg", ".png")
				.replace(".webp", ".png"));
		if (res.trophies != null)
			res.trophies.iter(function(t)
			{
				var newUrl:String = "";
				if (t.image_url.startsWith('https://m.'))
					newUrl = '${t.image_url.substring(0, 37)}1000${t.image_url.substr(40)}'.replace(".jpg", ".png").replace(".webp", ".png");
				else
				{
					newUrl = "https://s.gjcdn.net/assets/";
					newUrl += switch (t.image_url.substring(24).replace(".jpg", "").replace(".webp", ""))
					{
						case "trophy-bronze-1": "9c2c91d0";
						case "trophy-silver-1": "b46e352e";
						case "trophy-gold-1": "363ce2dc";
						case "trophy-platinum-1": "92e5330d";
						default: "";
					};
					newUrl += ".png";
				}
				t.image_url = newUrl;
			});
		if (res.responses != null)
			res.responses.iter(res2 -> res2 = formatImages(res2));
		return res;
	}
	
	/**
	 * Converts a `FlxGameJoltRequestType` instance into a piece of stringified URL.
	 * @param   request  The `FlxGameJoltRequestType` that will be converted to String.
	 * @param   signed   Whether to sign this conversion or not.
	 * @return	The new URL piece.
	 */
	function parseType(request:FlxGameJoltRequestType, signed:Bool = false):String
	{
		var command:String = "";
		var action:String = "";
		var params:Array<{name:String, value:String}> = [];
		
		switch (request)
		{
			case BATCH(parallel, breakOnError, requests):
				command = "batch";
				params.push({name: "parallel", value: '$parallel'});
				params.push({name: "break_on_error", value: '$breakOnError'});
				for (req in requests)
					params.push({name: "requests[]", value: parseType(req, true)});
			case DATA_FETCH(key, fromUser):
				command = "data-store";
				params.push({name: "key", value: key.urlEncode()});
				if (fromUser)
				{
					params.push({name: "username", value: FlxGameJolt.username});
					params.push({name: "user_token", value: FlxGameJolt.usertoken});
				}
			case DATA_GETKEYS(fromUser, pattern):
				command = "data-store";
				action = "get-keys";
				if (pattern != null && pattern != "")
					params.push({name: "pattern", value: pattern.urlEncode()});
				if (fromUser)
				{
					params.push({name: "username", value: FlxGameJolt.username});
					params.push({name: "user_token", value: FlxGameJolt.usertoken});
				}
			case DATA_REMOVE(key, fromUser):
				command = "data-store";
				action = "remove";
				params.push({name: "key", value: key.urlEncode()});
				if (fromUser)
				{
					params.push({name: "username", value: FlxGameJolt.username});
					params.push({name: "user_token", value: FlxGameJolt.usertoken});
				}
			case DATA_SET(key, data, toUser):
				command = "data-store";
				action = "set";
				params.push({name: "key", value: key.urlEncode()});
				params.push({name: "data", value: data.urlEncode()});
				if (toUser)
				{
					params.push({name: "username", value: FlxGameJolt.username});
					params.push({name: "user_token", value: FlxGameJolt.usertoken});
				}
			case DATA_UPDATE(key, operation, toUser):
				command = "data-store";
				action = "update";
				params.push({name: "key", value: key.urlEncode()});
				if (toUser)
				{
					params.push({name: "username", value: FlxGameJolt.username});
					params.push({name: "user_token", value: FlxGameJolt.usertoken});
				}
				switch (operation)
				{
					case Add(n):
						params.push({name: 'operation', value: 'add'});
						params.push({name: 'value', value: '$n'});
					case Substract(n):
						params.push({name: 'operation', value: 'substract'});
						params.push({name: 'value', value: '$n'});
					case Multiply(n):
						params.push({name: 'operation', value: 'multiply'});
						params.push({name: 'value', value: '$n'});
					case Divide(n):
						params.push({name: 'operation', value: 'divide'});
						params.push({name: 'value', value: '$n'});
					case Append(t):
						params.push({name: 'operation', value: 'append'});
						params.push({name: 'value', value: t.urlEncode()});
					case Prepend(t):
						params.push({name: 'operation', value: 'prepend'});
						params.push({name: 'value', value: t.urlEncode()});
				}
			case FRIENDS:
				command = "friends";
				params.push({name: "username", value: FlxGameJolt.username});
				params.push({name: "user_token", value: FlxGameJolt.usertoken});
			case TIME:
				command = "time";
			case USER_AUTH:
				command = "users";
				action = "auth";
				params.push({name: "username", value: FlxGameJolt.username});
				params.push({name: "user_token", value: FlxGameJolt.usertoken});
			case USER_FETCH(userOrID):
				command = "users";
				params.push({name: (~/[A-Za-z]+/).match(userOrID) ? "username" : "user_id", value: userOrID.replace(",", "%2C")});
			case SESSION_OPEN:
				command = "sessions";
				action = "open";
				params.push({name: "username", value: FlxGameJolt.username});
				params.push({name: "user_token", value: FlxGameJolt.usertoken});
			case SESSION_PING(active):
				command = "sessions";
				action = "ping";
				params.push({name: "status", value: active ? "active" : "idle"});
				params.push({name: "username", value: FlxGameJolt.username});
				params.push({name: "user_token", value: FlxGameJolt.usertoken});
			case SESSION_CHECK:
				command = "sessions";
				action = "check";
				params.push({name: "username", value: FlxGameJolt.username});
				params.push({name: "user_token", value: FlxGameJolt.usertoken});
			case SESSION_CLOSE:
				command = "sessions";
				action = "close";
				params.push({name: "username", value: FlxGameJolt.username});
				params.push({name: "user_token", value: FlxGameJolt.usertoken});
			case SCORES_ADD(score, sort, extra_data, table_id):
				command = "scores";
				action = "add";
				params.push({name: "score", value: score});
				params.push({name: "sort", value: '$sort'});
				if (extra_data != null && extra_data != "")
					params.push({name: "extra_data", value: extra_data.urlEncode()});
				if (table_id != null)
					params.push({name: "table_id", value: '$table_id'});
				if (FlxGameJolt.usertoken != "")
				{
					params.push({name: "username", value: FlxGameJolt.username});
					params.push({name: "user_token", value: FlxGameJolt.usertoken});
				}
				else
					params.push({name: "guest", value: FlxGameJolt.username});
			case SCORES_GETRANK(sort, table_id):
				command = "scores";
				action = "get-rank";
				params.push({name: "sort", value: '$sort'});
				if (table_id != null)
					params.push({name: "table_id", value: '$table_id'});
			case SCORES_FETCH(fromUser, table_id, limit, betterThan):
				command = "scores";
				if (table_id != null)
					params.push({name: "table_id", value: '$table_id'});
				if (limit != null)
					params.push({name: "limit", value: '$limit'});
				if (betterThan != null)
					params.push({name: betterThan < 0 ? "worse_than" : "better_than", value: '${Math.abs(betterThan)}'});
				if (fromUser)
				{
					if (FlxGameJolt.usertoken != "")
					{
						params.push({name: "username", value: FlxGameJolt.username});
						params.push({name: "user_token", value: FlxGameJolt.usertoken});
					}
					else
						params.push({name: "guest", value: FlxGameJolt.username});
				}
			case SCORES_TABLES:
				command = "scores";
				action = "tables";
			case TROPHIES_FETCH(achieved, trophy_id):
				command = "trophies";
				if (achieved != null)
					params.push({name: "achieved", value: '$achieved'});
				if (trophy_id != null)
					params.push({name: "trophy_id", value: '$trophy_id'});
				params.push({name: "username", value: FlxGameJolt.username});
				params.push({name: "user_token", value: FlxGameJolt.usertoken});
			case TROPHIES_ADD(trophy_id):
				command = "trophies";
				action = "add";
				params.push({name: "trophy_id", value: '$trophy_id'});
				params.push({name: "username", value: FlxGameJolt.username});
				params.push({name: "user_token", value: FlxGameJolt.usertoken});
			case TROPHIES_REMOVE(trophy_id):
				command = "trophies";
				action = "remove";
				params.push({name: "trophy_id", value: '$trophy_id'});
				params.push({name: "username", value: FlxGameJolt.username});
				params.push({name: "user_token", value: FlxGameJolt.usertoken});
		}
		
		var urlSection:String = '/$command${action != "" ? '/$action' : ""}?game_id=${FlxGameJolt.gameID}${[for (p in params) '&${p.name}=${p.value}'].join("")}';
		if (signed)
			urlSection = sign(urlSection).urlEncode();
		return urlSection;
	}
	
	/**
	 * Signs a piece of URL according to `usingMd5` parameter of the `FlxGameJolt` class.
	 * @param   daUrl  The old URL piece.
	 * @return  The new URL piece.
	 */
	function sign(daUrl:String):String
	{
		var urlToEncode:String = daUrl + FlxGameJolt.gameKey;
		return '$daUrl&signature=${FlxGameJolt.usingMd5 ? haxe.crypto.Md5.encode(urlToEncode) : haxe.crypto.Sha1.encode(urlToEncode)}';
	}
}
